name: 🚀 Feature Request
description: Suggest an idea for hassan
title: '[Feature]: '
labels: ['enhancement', 'triage']
assignees:
  - SampleAssignee

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! 🎉

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Before submitting, please make sure you have done the following
      options:
        - label: I have searched existing issues to avoid creating duplicates
          required: true
        - label: I have read the documentation
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I have also considered...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to this feature?
      options:
        - label: I would be willing to implement this feature
