name: Auto Merge

on:
  pull_request:
    types:
      [
        labeled,
        unlabeled,
        synchronize,
        opened,
        edited,
        ready_for_review,
        reopened,
      ]
  check_suite:
    types: [completed]
  status: {}

jobs:
  auto-merge:
    name: Auto Merge
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Auto merge
        uses: pascalgn/merge-action@v0.15.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          merge_commit_message: pull-request-title-and-description
          merge_forks: false
          merge_labels: automerge,!work in progress,!do not merge
          merge_remove_labels: automerge
          merge_commit_message_regex: '^(.+)(\r?\n)*$'
